# Generated by Django 5.2.3 on 2025-06-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='desc',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
