# Generated by Django 5.2.3 on 2025-06-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(default='bulbasaur.jpg', upload_to='pokepics'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='primary_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('fire', 'Fire'), ('water', 'Water'), ('electric', 'Electric'), ('grass', 'Grass'), ('ice', 'Ice'), ('fighting', 'Fighting'), ('poison', 'Poison'), ('ground', 'Ground'), ('flying', 'Flying'), ('psychic', 'Psychic'), ('bug', 'Bug'), ('rock', 'Rock'), ('ghost', 'Ghost'), ('dragon', 'Dragon'), ('dark', 'Dark'), ('steel', 'Steel'), ('fairy', 'Fairy')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='secondary_type',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('fire', 'Fire'), ('water', 'Water'), ('electric', 'Electric'), ('grass', 'Grass'), ('ice', 'Ice'), ('fighting', 'Fighting'), ('poison', 'Poison'), ('ground', 'Ground'), ('flying', 'Flying'), ('psychic', 'Psychic'), ('bug', 'Bug'), ('rock', 'Rock'), ('ghost', 'Ghost'), ('dragon', 'Dragon'), ('dark', 'Dark'), ('steel', 'Steel'), ('fairy', 'Fairy')], max_length=20, null=True),
        ),
    ]
